//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotBanking2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artisan
    {
        public int ArtisanId { get; set; }
        public string ArtisanName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    }
}
