//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotBanking2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class builder
    {
        public builder()
        {
            this.builder_comments = new HashSet<builder_comments>();
            this.builder_contacts = new HashSet<builder_contacts>();
            this.projects = new HashSet<project>();
            this.purchase_agreement = new HashSet<purchase_agreement>();
            this.traderefs = new HashSet<traderef>();
            this.master_planned_communities = new HashSet<master_planned_communities>();
        }
    
        public int id { get; set; }
        public string buildername { get; set; }
        public string optioneename { get; set; }
        public string contractorname { get; set; }
        public string website { get; set; }
        public Nullable<byte> current_litigation { get; set; }
        public string current_litigation_abstract { get; set; }
        public Nullable<byte> past_litigation { get; set; }
        public string past_litigation_abstract { get; set; }
        public string buildercol { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_modified { get; set; }
    
        public virtual ICollection<builder_comments> builder_comments { get; set; }
        public virtual ICollection<builder_contacts> builder_contacts { get; set; }
        public virtual ICollection<project> projects { get; set; }
        public virtual ICollection<purchase_agreement> purchase_agreement { get; set; }
        public virtual ICollection<traderef> traderefs { get; set; }
        public virtual ICollection<master_planned_communities> master_planned_communities { get; set; }
    }
}
