//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotBanking2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class builder_contacts
    {
        public int id { get; set; }
        public int builderid { get; set; }
        public int contactid { get; set; }
    
        public virtual builder builder { get; set; }
        public virtual contact contact { get; set; }
        public virtual phone phone { get; set; }
        public virtual email email { get; set; }
        public virtual address address { get; set; }
        public virtual traderef traderef { get; set; }
        public virtual trade_types trade_types { get; set; }
    }
}
