//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotBanking2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public comment()
        {
            this.builder_comments = new HashSet<builder_comments>();
            this.fund_comments = new HashSet<fund_comments>();
            this.project_comments = new HashSet<project_comments>();
            this.purchaseagreement_comments = new HashSet<purchaseagreement_comments>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string comments { get; set; }
        public Nullable<byte> is_private { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_modified { get; set; }
    
        public virtual ICollection<builder_comments> builder_comments { get; set; }
        public virtual ICollection<fund_comments> fund_comments { get; set; }
        public virtual ICollection<project_comments> project_comments { get; set; }
        public virtual ICollection<purchaseagreement_comments> purchaseagreement_comments { get; set; }
    }
}
