//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotBanking2.Models
{
    using System;
    using System.Data;
    using System.Data.Entity;
    using System.Linq;
    using System.Collections.Generic;

    
    public partial class contact
    {
        public contact()
        {
            this.addresses = new HashSet<address>();
            this.builder_contacts = new HashSet<builder_contacts>();
            this.emails = new HashSet<email>();
            this.fundmanager_contacts = new HashSet<fundmanager_contacts>();
            this.investor_contacts = new HashSet<investor_contacts>();
            this.phones = new HashSet<phone>();
            this.purchaseagreement_contacts = new HashSet<purchaseagreement_contacts>();
        }
    
        public int id { get; set; }
        public string company { get; set; }
        public string title { get; set; }
        public string name { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_modified { get; set; }
        public virtual phone phone { get; set; }
        public virtual email email { get; set; }
        public virtual address address { get; set; }

        public virtual ICollection<address> addresses { get; set; }
        public virtual ICollection<builder_contacts> builder_contacts { get; set; }
        public virtual ICollection<email> emails { get; set; }
        public virtual ICollection<fundmanager_contacts> fundmanager_contacts { get; set; }
        public virtual ICollection<investor_contacts> investor_contacts { get; set; }
        public virtual ICollection<phone> phones { get; set; }
        public virtual ICollection<purchaseagreement_contacts> purchaseagreement_contacts { get; set; }
        
        public void get(LotBankEntities db)
        {
            this.email = db.emails.Where(x => x.contactid == this.id).FirstOrDefault();
            this.phone = db.phones.Where(x => x.contactid == this.id).FirstOrDefault();
            this.address = db.addresses.Where(x => x.contactid == this.id).FirstOrDefault();
        }

        public void update(LotBankEntities db)
        {
            var contact = db.contacts.Find(this.id);
            contact.date_modified = DateTime.Now;
            contact.company = this.company;
            contact.name = this.name;
            contact.title = this.title;
            

        }
    
    }
}
