//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotBanking2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diligence_ent
    {
        public int id { get; set; }
        public int projectid { get; set; }
        public string naos_comments { get; set; }
        public Nullable<byte> naos_requirements { get; set; }
        public string restrictions_other { get; set; }
        public string plat_comments { get; set; }
        public string plat_status { get; set; }
        public string plat_final { get; set; }
        public string plat_stipulations { get; set; }
        public string zoning_designation_ordinance { get; set; }
        public Nullable<byte> zoning_development_agreement { get; set; }
        public Nullable<byte> zoning_jurisdiction_city { get; set; }
        public string zoning_stipulations { get; set; }
        public string zoning_vesting_status { get; set; }
        public string zoning_density { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_modified { get; set; }
    
        public virtual project project { get; set; }
    }
}
