//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotBanking2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diligence_financial
    {
        public int id { get; set; }
        public int projectid { get; set; }
        public string proforma_gross_margin { get; set; }
        public string proforma_net_margin { get; set; }
        public string model_sale_leaseback_investor { get; set; }
        public string tax_bill_current { get; set; }
        public Nullable<int> dev_budget_onsite { get; set; }
        public Nullable<int> dev_budget_offsite { get; set; }
        public string fees_impact { get; set; }
        public string fees_school { get; set; }
        public string fees_other { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_modified { get; set; }
    
        public virtual project project { get; set; }
    }
}
