//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotBanking2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diligence_hoa
    {
        public int id { get; set; }
        public int projectid { get; set; }
        public System.DateTime formation_date { get; set; }
        public Nullable<byte> formation_docs { get; set; }
        public Nullable<byte> ccr_docs { get; set; }
        public Nullable<byte> reserve_study_docs { get; set; }
        public Nullable<System.DateTime> turnover_date { get; set; }
        public Nullable<decimal> annual_budget { get; set; }
        public Nullable<decimal> unit_per_month { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_modified { get; set; }
    
        public virtual project project { get; set; }
    }
}
