//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotBanking2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class entity
    {
        public int id { get; set; }
        public int investorid { get; set; }
        public string entity_name { get; set; }
        public string corporation_name { get; set; }
        public string tax_id { get; set; }
        public Nullable<byte> tax_exempt { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_modified { get; set; }
    
        public virtual investor investor { get; set; }
    }
}
