//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotBanking2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class funds_received
    {
        public int id { get; set; }
        public int fundid { get; set; }
        public int investorid { get; set; }
        public decimal received_amount { get; set; }
        public System.DateTime received_date { get; set; }
        public string details { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_modified { get; set; }
    
        public virtual fund fund { get; set; }
        public virtual investor investor { get; set; }
    }
}
