//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotBanking2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fund_manager
    {
        public int id { get; set; }
        public int fundid { get; set; }
        public string legal_entity_name { get; set; }
        public string state_of_incorp { get; set; }
        public string tax_id { get; set; }
        public Nullable<System.DateTime> setup_date { get; set; }
        public Nullable<System.DateTime> dissolution_date { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_modified { get; set; }
    
        public virtual fund fund { get; set; }
    }
}
