//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotBanking2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fund
    {
        public fund()
        {
            this.fund_comments = new HashSet<fund_comments>();
            this.fund_leverage = new HashSet<fund_leverage>();
            this.fund_manager = new HashSet<fund_manager>();
            this.fund_offering = new HashSet<fund_offering>();
            this.fundmanager_contacts = new HashSet<fundmanager_contacts>();
            this.funds_committed = new HashSet<funds_committed>();
            this.funds_invested = new HashSet<funds_invested>();
            this.funds_received = new HashSet<funds_received>();
            this.purchase_agreement = new HashSet<purchase_agreement>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string legal_name { get; set; }
        public Nullable<int> companytypeid { get; set; }
        public Nullable<System.DateTime> formationdate { get; set; }
        public string federal_id { get; set; }
        public string state_id { get; set; }
        public string phone { get; set; }
        public string zipcode { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_modified { get; set; }
    
        public virtual company_types company_types { get; set; }
        public virtual ICollection<fund_comments> fund_comments { get; set; }
        public virtual ICollection<fund_leverage> fund_leverage { get; set; }
        public virtual ICollection<fund_manager> fund_manager { get; set; }
        public virtual ICollection<fund_offering> fund_offering { get; set; }
        public virtual ICollection<fundmanager_contacts> fundmanager_contacts { get; set; }
        public virtual ICollection<funds_committed> funds_committed { get; set; }
        public virtual ICollection<funds_invested> funds_invested { get; set; }
        public virtual ICollection<funds_received> funds_received { get; set; }
        public virtual ICollection<purchase_agreement> purchase_agreement { get; set; }
    }
}
