//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotBanking2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fund_offering
    {
        public int id { get; set; }
        public int fundid { get; set; }
        public decimal project_irr { get; set; }
        public decimal project_wdp { get; set; }
        public decimal project_irr_leveraged { get; set; }
        public decimal project_wdp_leveraged { get; set; }
        public decimal dquity_required { get; set; }
        public decimal Pref_rate { get; set; }
        public decimal hurdle_rate { get; set; }
        public decimal split_to_hurdle { get; set; }
        public decimal split_after_hurdle { get; set; }
        public decimal participation_cbh { get; set; }
        public decimal investor_irr_forecast { get; set; }
        public string equity_comments { get; set; }
        public decimal underwriting_fee { get; set; }
        public decimal management_fee_cbh { get; set; }
        public decimal Management_fee_collected { get; set; }
        public decimal cashflow_forecast { get; set; }
        public decimal cashflow_actual { get; set; }
        public string base_economics_comments { get; set; }
        public Nullable<System.DateTime> ppm_date { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_modified { get; set; }
    
        public virtual fund fund { get; set; }
    }
}
