//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotBanking2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LotBankEntities : DbContext
    {
        public LotBankEntities()
            : base("name=LotBankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<address> addresses { get; set; }
        public DbSet<builder_comments> builder_comments { get; set; }
        public DbSet<builder_contacts> builder_contacts { get; set; }
        public DbSet<builder> builders { get; set; }
        public DbSet<comment> comments { get; set; }
        public DbSet<company_types> company_types { get; set; }
        public DbSet<contact> contacts { get; set; }
        public DbSet<diligence_ent> diligence_ent { get; set; }
        public DbSet<diligence_financial> diligence_financial { get; set; }
        public DbSet<diligence_hoa> diligence_hoa { get; set; }
        public DbSet<diligence_location> diligence_location { get; set; }
        public DbSet<diligence_plans> diligence_plans { get; set; }
        public DbSet<diligence_reports> diligence_reports { get; set; }
        public DbSet<diligence_title> diligence_title { get; set; }
        public DbSet<diligence_utilities> diligence_utilities { get; set; }
        public DbSet<email> emails { get; set; }
        public DbSet<entity> entities { get; set; }
        public DbSet<fund_comments> fund_comments { get; set; }
        public DbSet<fund_leverage> fund_leverage { get; set; }
        public DbSet<fund_manager> fund_manager { get; set; }
        public DbSet<fund_offering> fund_offering { get; set; }
        public DbSet<fundmanager_contacts> fundmanager_contacts { get; set; }
        public DbSet<fund> funds { get; set; }
        public DbSet<funds_committed> funds_committed { get; set; }
        public DbSet<funds_invested> funds_invested { get; set; }
        public DbSet<funds_received> funds_received { get; set; }
        public DbSet<investor_contacts> investor_contacts { get; set; }
        public DbSet<investor_types> investor_types { get; set; }
        public DbSet<investor> investors { get; set; }
        public DbSet<phone> phones { get; set; }
        public DbSet<plan_types> plan_types { get; set; }
        public DbSet<project_comments> project_comments { get; set; }
        public DbSet<project_leverage> project_leverage { get; set; }
        public DbSet<project_sizes> project_sizes { get; set; }
        public DbSet<project> projects { get; set; }
        public DbSet<purchase_agreement> purchase_agreement { get; set; }
        public DbSet<purchaseagreement_comments> purchaseagreement_comments { get; set; }
        public DbSet<purchaseagreement_contacts> purchaseagreement_contacts { get; set; }
        public DbSet<report_types> report_types { get; set; }
        public DbSet<trade_types> trade_types { get; set; }
        public DbSet<traderef> traderefs { get; set; }
        public DbSet<type> types { get; set; }
        public DbSet<utility_providers> utility_providers { get; set; }
        public DbSet<master_planned_communities> master_planned_communities { get; set; }
        public DbSet<Artisan> Artisans { get; set; }
        public DbSet<aoeu_htns> aoeu_htns { get; set; }
    }
}
