//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotBanking2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_planned_communities
    {
        public master_planned_communities()
        {
            this.projects = new HashSet<project>();
        }
    
        public int id { get; set; }
        public int builderid { get; set; }
        public string name { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_modified { get; set; }
    
        public virtual builder builder { get; set; }
        public virtual ICollection<project> projects { get; set; }
    }
}
