//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotBanking2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_types
    {
        public plan_types()
        {
            this.diligence_plans = new HashSet<diligence_plans>();
        }
    
        public int id { get; set; }
        public int typeid { get; set; }
    
        public virtual ICollection<diligence_plans> diligence_plans { get; set; }
        public virtual type type { get; set; }
    }
}
