//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotBanking2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_sizes
    {
        public int id { get; set; }
        public int projectid { get; set; }
        public int parcel_acres { get; set; }
        public int parcel_lots { get; set; }
        public int lotsize_min { get; set; }
        public int lotsize_max { get; set; }
        public int setbacks_front { get; set; }
        public int setbacks_rear { get; set; }
        public int setbacks_side { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_modified { get; set; }
    
        public virtual project project { get; set; }
    }
}
