//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotBanking2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_agreement
    {
        public purchase_agreement()
        {
            this.purchaseagreement_contacts = new HashSet<purchaseagreement_contacts>();
            this.purchaseagreement_comments = new HashSet<purchaseagreement_comments>();
        }
    
        public int id { get; set; }
        public int fundid { get; set; }
        public int projectid { get; set; }
        public int builderid { get; set; }
        public Nullable<byte> purchasecontract { get; set; }
        public string sellingentity { get; set; }
        public string sellingentitytype { get; set; }
        public string buyingentity { get; set; }
        public string buyingentitytype { get; set; }
        public Nullable<System.DateTime> opendate { get; set; }
        public Nullable<System.DateTime> closedate { get; set; }
        public Nullable<decimal> earnest_money { get; set; }
        public Nullable<byte> refundable { get; set; }
        public Nullable<byte> assignment { get; set; }
        public Nullable<decimal> purchase_price { get; set; }
        public Nullable<decimal> current_purchase_price { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_modified { get; set; }
    
        public virtual builder builder { get; set; }
        public virtual fund fund { get; set; }
        public virtual project project { get; set; }
        public virtual ICollection<purchaseagreement_contacts> purchaseagreement_contacts { get; set; }
        public virtual ICollection<purchaseagreement_comments> purchaseagreement_comments { get; set; }
    }
}
