//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotBanking2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_types
    {
        public report_types()
        {
            this.diligence_reports = new HashSet<diligence_reports>();
        }
    
        public int id { get; set; }
        public int typeid { get; set; }
    
        public virtual ICollection<diligence_reports> diligence_reports { get; set; }
        public virtual type type { get; set; }
    }
}
