//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotBanking2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utility_providers
    {
        public utility_providers()
        {
            this.diligence_utilities = new HashSet<diligence_utilities>();
        }
    
        public int id { get; set; }
        public string provider { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_modified { get; set; }
    
        public virtual ICollection<diligence_utilities> diligence_utilities { get; set; }
    }
}
